### PR TITLE
Waila Integration Improvements

### PR DESCRIPTION
**Pull request by pupnewfster**
Shows how much Pollution a TileEntity is producing. This includes both reductions in pollution and increases in pollution.

This is useful for large modpacks as it makes it easier for players to track down the causes of pollution.

### CODE REVIEW

**Comment by Artem226** [comment]
I don't think it is advisable, a creation of a new item would suit this task better because it's good for the balance(you need to craft the item) and realism. So you can examine pollution production when you are really concerned about it (in survival mode) or just take the item from the creative inventory if you are the admin.

**Comment by pupnewfster** [comment]
I suppose it is not fully accurate to realism. Granted in real life you can lookup how much pollution certain machines would give off.
Two other alternatives if you really don't want it to be shown (even though players could look in the config anyways):
- Add a "normal" config that lets people enable or disable it. I say "normal" because it is for changing options of the mod rather than values.
- If there is a pollution analyzer in the chunk or once you craft a pollution analyzer you are able to see the pollution values blocks emit.

**Comment by MattChamberlain** [comment]
I think that any information that could be gained outside the game itself should be more easily accessible in game. It is why mods tend to create guide books instead of just assuming that people will go to the wiki page to understand how the mod works. To me, adding waila support just allows me to enjoy the mod more instead of manually going to the wiki/config to lookup pollution values. I definitely support creating a config to enable or disable though and possibly even have the value default to disabled.

**Comment by Artem226** [comment]
Well, then. Although I think it should be shown at least when you are pressing shift(or another configured key) to avoid the overflow with information.

**Comment by pupnewfster** [comment]
That sounds reasonable, would you like me to attempt to implement that? (for now probably would use whatever crouch is assigned to as most things that default to SHIFT use). And then later if you choose you can add a config option to disable it.

**Comment by Artem226** [comment]
Yes, surely.

**Comment by Artem226** [comment]
Moreover, I'm planning to add JEI support and I wonder if adding pollution config information(tile entities, sources and effects) as a JEI categories would be useful.

**Comment by pupnewfster** [comment]
@Artem226 I implemented the change show it only shows the detailed pollution values while sneaking. I wanted to make it tell them something along the lines of "Press <SHIFT> to view..." but I had to tell them to sneak as I could not figure out how to get the players crouch key dynamically.

**Pull request merged**
